AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  BookmarksToolsLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: BookmarksToolsLayerArn

  KmsKeyId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: KmsKeyId

Resources:
  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE