AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  BookmarksChatBotSnsTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: BookmarksChatBotSnsTopicArn

  BookmarksToolsLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: BookmarksToolsLayerArn

  KmsKeyId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: KmsKeyId

  Environ:
    Type: AWS::SSM::Parameter::Value<String>
    Default: Environ

  StageName:
    Type: String
    Default: v1

Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
    MemorySize: 256
    AutoPublishAlias: !Ref Environ
    Environment:
      Variables:
        AWS_ENV: !Ref Environ
        ARTICLES_TABLE_NAME: !Ref ArticlesTable
        KMS_KEY_ID: !Ref KmsKeyId
        BOOKMARKS_USER_ID: C345859B-0C0F-45FA-AFF9-C480E34F0F36
    Layers:
      - !Ref BookmarksToolsLayerArn

Resources:
  ArticlesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  CreateEncryptedConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_encrypted_config
      Handler: index.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
              Resource:
                - "*"
      Events:
        PostConfig:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /config/encrypt
            Method: POST

  CreateEncryptedConfigLogResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_resources.yml
      Parameters:
        FunctionName: !Ref CreateEncryptedConfigFunction
        AlartActionTopicArn: !Ref BookmarksChatBotSnsTopicArn

Outputs:
  ApiBaseUrl:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
  CreateEncryptedConfigUrl:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/config/encrypt