AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  BookmarksChatBotSnsTopicArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: BookmarksChatBotSnsTopicArn

  BookmarksToolsLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: BookmarksToolsLayerArn

  TwitterLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: TwitterLayerArn

  KmsKeyId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: KmsKeyId

  Environ:
    Type: AWS::SSM::Parameter::Value<String>
    Default: Environ

  ArticlesTableName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ArticlesTableName

  ArticlesTableStreamArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ArticlesTableStreamArn

  StageName:
    Type: String
    Default: v1

Globals:
  Function:
    Runtime: python3.7
    Timeout: 30
    MemorySize: 256
    AutoPublishAlias: !Ref Environ
    Environment:
      Variables:
        AWS_ENV: !Ref Environ
        BOOKMARKS_USER_ID: C345859B-0C0F-45FA-AFF9-C480E34F0F36
        KMS_KEY_ID: !Ref KmsKeyId
        ARTICLES_TABLE_NAME: !Ref ArticlesTableName
    Layers:
      - !Ref BookmarksToolsLayerArn

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  CreateEncryptedConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/create_encrypted_config
      Handler: index.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
              Resource:
                - "*"
      Events:
        PostConfig:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /config/encrypt
            Method: POST

  CreateEncryptedConfigLogResources:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_resources.yml
      Parameters:
        FunctionName: !Ref CreateEncryptedConfigFunction
        AlartActionTopicArn: !Ref BookmarksChatBotSnsTopicArn

  BookmarkletRegistFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/bookmarklet_regist
      Handler: index.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
              Resource:
                - "*"
      Events:
        BookmarkletRegistArticle:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /bookmarklet/regist
            Method: GET

  BookmarkletRegistLogResource:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_resources.yml
      Parameters:
        FunctionName: !Ref BookmarkletRegistFunction
        AlartActionTopicArn: !Ref BookmarksChatBotSnsTopicArn

  BookmarkletResultFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/bookmarklet_result
      Handler: index.handler
      Events:
        BookmarksRegistResult:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /bookmarklet/result
            Method: GET

  BookmarkletResultLogResource:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: log_resources.yml
      Parameters:
        FunctionName: !Ref BookmarkletResultFunction
        AlartActionTopicArn: !Ref BookmarksChatBotSnsTopicArn

  TweetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/tweet
      Handler: index.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:Encrypt
              Resource:
                - "*"
      Layers:
        - !Ref TwitterLayerArn
      Events:
        Insert:
          Type: DynamoDB
          Properties:
            Stream: !Ref ArticlesTableStreamArn
            StartingPosition: LATEST
            BatchSize: 1


Outputs:
  ApiBaseUrl:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}
  CreateEncryptedConfigUrl:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/config/encrypt
  BookmarkletRegistUrl:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/bookmarklet/regist